set -e
true
true
/usr/local/programs/SPAdes-3.14.1-Linux/bin/spades-hammer /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/corrected/configs/config.info
/usr/bin/python /usr/local/programs/SPAdes-3.14.1-Linux/share/spades/spades_pipeline/scripts/compress_all.py --input_file /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/corrected/corrected.yaml --ext_python_modules_home /usr/local/programs/SPAdes-3.14.1-Linux/share/spades --max_threads 4 --output_dir /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/corrected --gzip_output
true
true
/usr/local/programs/SPAdes-3.14.1-Linux/bin/spades-core /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K21/configs/config.info
/usr/local/programs/SPAdes-3.14.1-Linux/bin/spades-core /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K33/configs/config.info
/usr/local/programs/SPAdes-3.14.1-Linux/bin/spades-core /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K55/configs/config.info
/usr/local/programs/SPAdes-3.14.1-Linux/bin/spades-core /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K77/configs/config.info
/usr/local/programs/SPAdes-3.14.1-Linux/bin/spades-core /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K99/configs/config.info
/usr/local/programs/SPAdes-3.14.1-Linux/bin/spades-core /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K127/configs/config.info
/usr/bin/python /usr/local/programs/SPAdes-3.14.1-Linux/share/spades/spades_pipeline/scripts/copy_files.py /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K127/before_rr.fasta /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/before_rr.fasta /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K127/assembly_graph_after_simplification.gfa /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/assembly_graph_after_simplification.gfa /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K127/final_contigs.fasta /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/contigs.fasta /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K127/first_pe_contigs.fasta /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/first_pe_contigs.fasta /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K127/strain_graph.gfa /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/strain_graph.gfa /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K127/scaffolds.fasta /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/scaffolds.fasta /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K127/scaffolds.paths /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/scaffolds.paths /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K127/assembly_graph_with_scaffolds.gfa /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/assembly_graph_with_scaffolds.gfa /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K127/assembly_graph.fastg /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/assembly_graph.fastg /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/K127/final_contigs.paths /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/contigs.paths
true
/usr/bin/python /usr/local/programs/SPAdes-3.14.1-Linux/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/scaffolds.fasta --misc_dir /home/fan.shua/Personal_Project/SARS-CoV-2_patient_specimen/SARS-CoV-2/misc --threshold_for_breaking_scaffolds 3
true
